title: COVID-19 Social Distance Strategies
url: ""
baseurl: ""

markdown: kramdown

tracking_id: #

footer: yes
footer_url: ""
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Team"
   link: "team"
 - name: "Contact"
   link: "contact"

github: [metadata]